# Generated by Django 5.2.1 on 2025-06-08 15:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCarTehran',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('full_id', models.CharField(max_length=255)),
                ('osm_id', models.CharField(max_length=255)),
                ('osm_type', models.CharField(max_length=255)),
                ('shop', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'shop_car_tehran_1',
                'managed': False,
            },
        ),
    ]
