# Generated by Django 4.2.23 on 2025-06-14 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_chatrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatrequest',
            name='is_video_call',
        ),
        migrations.AddField(
            model_name='chatrequest',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='chatrequest',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.shopcartehran'),
        ),
    ]
