# Generated by Django 4.2.23 on 2025-06-15 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('year', models.IntegerField()),
                ('condition', models.CharField(choices=[('new', 'نو'), ('used', 'دست\u200cدوم')], max_length=10)),
                ('fuel_type', models.CharField(choices=[('gasoline', 'بنزین'), ('dual', 'دوگانه\u200cسوز')], max_length=20)),
                ('mileage', models.IntegerField(default=0)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='map.shopcartehran')),
            ],
        ),
    ]
