# Generated by Django 4.2.23 on 2025-07-16 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrequest',
            name='ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.advertisement'),
        ),
    ]
